name: hotel_app
description: Test project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0
  retrofit: ^4.0.1
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.9.0
  dio: ^5.3.2
  equatable: ^2.0.5
  meta: ^1.9.1
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  bloc: ^8.1.2
  mask_text_input_formatter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^7.0.8
  build_runner: ^2.4.6
  test: ^1.24.3
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/San Francisco Pro Display/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/San Francisco Pro Display/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/San Francisco Pro Display/SF-Pro-Display-Semibold.otf
          weight: 600

